# Generated by Django 3.2 on 2022-10-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_total_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='total_like',
            new_name='total_likes',
        ),
    ]
